//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazysoft.OTRRemote.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TVBrowser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TVBrowser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crazysoft.OTRRemote.Lang.TVBrowser", typeof(TVBrowser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string FrmWizard_btnClose {
            get {
                return ResourceManager.GetString("FrmWizard_btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next &gt;.
        /// </summary>
        internal static string FrmWizard_btnNext {
            get {
                return ResourceManager.GetString("FrmWizard_btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; &amp;Previous.
        /// </summary>
        internal static string FrmWizard_btnPrevious {
            get {
                return ResourceManager.GetString("FrmWizard_btnPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Start TV-Browser.
        /// </summary>
        internal static string FrmWizard_lblHeader {
            get {
                return ResourceManager.GetString("FrmWizard_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Open the Capture Plugin Settings.
        /// </summary>
        internal static string FrmWizard_lblHeader_Step2 {
            get {
                return ResourceManager.GetString("FrmWizard_lblHeader_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: Create a new device.
        /// </summary>
        internal static string FrmWizard_lblHeader_Step3 {
            get {
                return ResourceManager.GetString("FrmWizard_lblHeader_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4: Select OTR Remote as application.
        /// </summary>
        internal static string FrmWizard_lblHeader_Step4 {
            get {
                return ResourceManager.GetString("FrmWizard_lblHeader_Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 5: Configure the recording parameters.
        /// </summary>
        internal static string FrmWizard_lblHeader_Step5 {
            get {
                return ResourceManager.GetString("FrmWizard_lblHeader_Step5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 6: Configure the plugin settings.
        /// </summary>
        internal static string FrmWizard_lblHeader_Step6 {
            get {
                return ResourceManager.GetString("FrmWizard_lblHeader_Step6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 7: Use it!.
        /// </summary>
        internal static string FrmWizard_lblHeader_Step7 {
            get {
                return ResourceManager.GetString("FrmWizard_lblHeader_Step7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will now guide you thorugh the configuration of TV-Browser for OTR Remote. Unfortunately, this can&apos;t be done automatically up to now..
        /// </summary>
        internal static string FrmWizard_lblPage1Header {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, you have to start TV-Browser, if you haven&apos;t done yet. Simply open TV-Browser as you normally would do..
        /// </summary>
        internal static string FrmWizard_lblPage1Text1 {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage1Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, open the Capture Plugin Settings dialog by clicking &quot;Plugins&quot; in the menu bar and selecting &quot;Capture Plugin&quot;..
        /// </summary>
        internal static string FrmWizard_lblPage2Text1 {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage2Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the settings dialog, create a new device by changing to the &quot;Devices&quot; tab and clicking on &quot;Add Device&quot;. Enter the name &quot;OnlineTvRecorder&quot; and select the Default Driver. Click OK..
        /// </summary>
        internal static string FrmWizard_lblPage3Text1 {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage3Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the Application tab, copy following text into the Application field:.
        /// </summary>
        internal static string FrmWizard_lblPage4Text1 {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage4Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete:.
        /// </summary>
        internal static string FrmWizard_lblPage5Delete {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage5Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record:.
        /// </summary>
        internal static string FrmWizard_lblPage5Record {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage5Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the Parameter tab, copy following text into the Record and the Delete field:.
        /// </summary>
        internal static string FrmWizard_lblPage5Text1 {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage5Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the Settings tab, set the options as shown on the image below. If you know, what these settings do, you can also set them as they fit best for you..
        /// </summary>
        internal static string FrmWizard_lblPage6Text1 {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage6Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have now finished configuring TV-Browser for OTR Remote. After clicking OK in both windows, you are ready to record!.
        /// </summary>
        internal static string FrmWizard_lblPage7Header {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage7Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can simply record TV shows by right-clicking them and selecting &quot;Record&quot; from the context menu. Close this wizard by clicking Close in the right bottom corner..
        /// </summary>
        internal static string FrmWizard_lblPage7Text1 {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage7Text1", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FrmWizard_pbHeader {
            get {
                object obj = ResourceManager.GetObject("FrmWizard_pbHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrmWizard_pbPage1Shortcut {
            get {
                object obj = ResourceManager.GetObject("FrmWizard_pbPage1Shortcut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrmWizard_pbPage2CapturePlugin {
            get {
                object obj = ResourceManager.GetObject("FrmWizard_pbPage2CapturePlugin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrmWizard_pbPage3NewDevice {
            get {
                object obj = ResourceManager.GetObject("FrmWizard_pbPage3NewDevice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrmWizard_pbPage4ApplicationTab {
            get {
                object obj = ResourceManager.GetObject("FrmWizard_pbPage4ApplicationTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrmWizard_pbPage5ParameterTab {
            get {
                object obj = ResourceManager.GetObject("FrmWizard_pbPage5ParameterTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrmWizard_pbPage6SettingsTab {
            get {
                object obj = ResourceManager.GetObject("FrmWizard_pbPage6SettingsTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -r -s=&quot;{channel_name}&quot; -sd={concat(start_year, &quot;-&quot;, leadingZero(start_month, &quot;2&quot;), &quot;-&quot;, leadingZero(start_day, &quot;2&quot;))} -st={concat(leadingZero(start_hour, &quot;2&quot;), &quot;:&quot;, leadingZero(start_minute, &quot;2&quot;))} -et={concat(leadingZero(end_hour, &quot;2&quot;), &quot;:&quot;, leadingZero(end_minute, &quot;2&quot;))} -t=&quot;{title}&quot; -g=&quot;{genre}&quot;.
        /// </summary>
        internal static string FrmWizard_tbPage5DeleteText {
            get {
                return ResourceManager.GetString("FrmWizard_tbPage5DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -a -s=&quot;{channel_name}&quot; -sd={concat(start_year, &quot;-&quot;, leadingZero(start_month, &quot;2&quot;), &quot;-&quot;, leadingZero(start_day, &quot;2&quot;))} -st={concat(leadingZero(start_hour, &quot;2&quot;), &quot;:&quot;, leadingZero(start_minute, &quot;2&quot;))} -et={concat(leadingZero(end_hour, &quot;2&quot;), &quot;:&quot;, leadingZero(end_minute, &quot;2&quot;))} -t=&quot;{title}&quot; -g=&quot;{genre}&quot;.
        /// </summary>
        internal static string FrmWizard_tbPage5RecordText {
            get {
                return ResourceManager.GetString("FrmWizard_tbPage5RecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV-Browser Plugin Installation Wizard.
        /// </summary>
        internal static string FrmWizard_Title {
            get {
                return ResourceManager.GetString("FrmWizard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have write access to the application path. Please run OTR Remote as an administrator..
        /// </summary>
        internal static string Plugin_Error_AccessDenied {
            get {
                return ResourceManager.GetString("Plugin_Error_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application path you have entered is invalid. Please make sure you entered the application&apos;s path, not the plugin folder..
        /// </summary>
        internal static string Plugin_Error_Invalid_Path {
            get {
                return ResourceManager.GetString("Plugin_Error_Invalid_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Path.
        /// </summary>
        internal static string Plugin_Settings_Path {
            get {
                return ResourceManager.GetString("Plugin_Settings_Path", resourceCulture);
            }
        }
    }
}
