//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazysoft.OTRRemote.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TVgenial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TVgenial() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crazysoft.OTRRemote.Lang.TVgenial", typeof(TVgenial).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVgenial Version 4 saves its plugins in the application directory. Unfortunately, you don&apos;t have write access to it. Please run OTR Remote again as an Administrator..
        /// </summary>
        internal static string Plugin_Error_AccessDenied_Interface {
            get {
                return ResourceManager.GetString("Plugin_Error_AccessDenied_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have write access to the recording script path. Please enter  another path..
        /// </summary>
        internal static string Plugin_Error_AccessDenied_Script {
            get {
                return ResourceManager.GetString("Plugin_Error_AccessDenied_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of the Recording Script..
        /// </summary>
        internal static string Plugin_Error_Name {
            get {
                return ResourceManager.GetString("Plugin_Error_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVgenial was found on your computer, but it seems, that the installation is corrupt. Please try reinstalling TVgenial..
        /// </summary>
        internal static string Plugin_Error_NoInstallDir {
            get {
                return ResourceManager.GetString("Plugin_Error_NoInstallDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the path to TVgenial..
        /// </summary>
        internal static string Plugin_Error_Path {
            get {
                return ResourceManager.GetString("Plugin_Error_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default Recording Interface.
        /// </summary>
        internal static string Plugin_Settings_Default {
            get {
                return ResourceManager.GetString("Plugin_Settings_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Deletion of Recordings.
        /// </summary>
        internal static string Plugin_Settings_Delete {
            get {
                return ResourceManager.GetString("Plugin_Settings_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Script Name.
        /// </summary>
        internal static string Plugin_Settings_Name {
            get {
                return ResourceManager.GetString("Plugin_Settings_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Script Path.
        /// </summary>
        internal static string Plugin_Settings_Path {
            get {
                return ResourceManager.GetString("Plugin_Settings_Path", resourceCulture);
            }
        }
    }
}
