//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.3053
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazysoft.OTRRemote.Lang {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OTRRemote {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OTRRemote() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crazysoft.OTRRemote.Lang.OTRRemote", typeof(OTRRemote).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete &quot;{0}&quot; from {1} at {2}? If you delete the recording, it will not be recorded, or you will not be able to decode it. ähnelt.
        /// </summary>
        internal static string CmdLine_DeleteMsg_Text {
            get {
                return ResourceManager.GetString("CmdLine_DeleteMsg_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm deletion ähnelt.
        /// </summary>
        internal static string CmdLine_DeleteMsg_Title {
            get {
                return ResourceManager.GetString("CmdLine_DeleteMsg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No action set (-a for Add, -r for Remove) ähnelt.
        /// </summary>
        internal static string CmdLine_Error_Action {
            get {
                return ResourceManager.GetString("CmdLine_Error_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No end time set or wrong format (-et=hh:mm; e.g.: -et=22:05) ähnelt.
        /// </summary>
        internal static string CmdLine_Error_EndTime {
            get {
                return ResourceManager.GetString("CmdLine_Error_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No start date set or wrong format (-sd=yyyy-mm-dd; e.g.: -sd=2006-04-13) ähnelt.
        /// </summary>
        internal static string CmdLine_Error_StartDate {
            get {
                return ResourceManager.GetString("CmdLine_Error_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No start time set or wrong format (-st=hh:mm; e.g.: -st=20:15) ähnelt.
        /// </summary>
        internal static string CmdLine_Error_StartTime {
            get {
                return ResourceManager.GetString("CmdLine_Error_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No station set (-s=&quot;Station Name&quot;) ähnelt.
        /// </summary>
        internal static string CmdLine_Error_Station {
            get {
                return ResourceManager.GetString("CmdLine_Error_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Errors while trying to add a recording:
        ///
        ///{0}
        ///Would you like to read the Recording Help? ähnelt.
        /// </summary>
        internal static string CmdLine_ErrorMsg_Text {
            get {
                return ResourceManager.GetString("CmdLine_ErrorMsg_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recording Error ähnelt.
        /// </summary>
        internal static string CmdLine_ErrorMsg_Title {
            get {
                return ResourceManager.GetString("CmdLine_ErrorMsg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Close ähnelt.
        /// </summary>
        internal static string FrmHelp_btnClose {
            get {
                return ResourceManager.GetString("FrmHelp_btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commandline Arguments: ähnelt.
        /// </summary>
        internal static string FrmHelp_lblCmdArgsHeader {
            get {
                return ResourceManager.GetString("FrmHelp_lblCmdArgsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -a Add a recording.
        ///-r Remove a recording.
        ///-h Show this help.
        ///-s Short name of the TV station to record.
        ///-sd Start date of the recording. (Format: yyyy-mm-dd)
        ///-st Start time of the recording. (Format: hh:mm)
        ///-et End time of the recording. (Format: hh:mm) ähnelt.
        /// </summary>
        internal static string FrmHelp_lblCmdArgsText {
            get {
                return ResourceManager.GetString("FrmHelp_lblCmdArgsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recording Help ähnelt.
        /// </summary>
        internal static string FrmHelp_lblHeader {
            get {
                return ResourceManager.GetString("FrmHelp_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes: ähnelt.
        /// </summary>
        internal static string FrmHelp_lblNotesHeader {
            get {
                return ResourceManager.GetString("FrmHelp_lblNotesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If an argument is shown within quotation marks, you have to write them too!
        ///Username, password and timezone don&apos;t have to be set if you configured them in the Control Panel. ähnelt.
        /// </summary>
        internal static string FrmHelp_lblNotesText {
            get {
                return ResourceManager.GetString("FrmHelp_lblNotesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optional Arguments: ähnelt.
        /// </summary>
        internal static string FrmHelp_lblOptionalArgsHeader {
            get {
                return ResourceManager.GetString("FrmHelp_lblOptionalArgsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -t Title of the TV show to record.
        ///-g Genre of the TV show.
        ///-u Your OTR username or e-mail address.
        ///-p Your OTR password.
        ///-tz Timezone: The difference to GMT in hours. (e.g. Middle Europe: 1) ähnelt.
        /// </summary>
        internal static string FrmHelp_lblOptionalArgsText {
            get {
                return ResourceManager.GetString("FrmHelp_lblOptionalArgsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usage: ähnelt.
        /// </summary>
        internal static string FrmHelp_lblUsageHeader {
            get {
                return ResourceManager.GetString("FrmHelp_lblUsageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OTRRemote.exe -a|-r -s=&quot;Station&quot; -sd=yyyy-mm-dd -st=hh:mm -et=hh:mm [-t=&quot;Title&quot;] [-u=&quot;User&quot;] [-p=&quot;Password&quot;] [-tz=Timezone] ähnelt.
        /// </summary>
        internal static string FrmHelp_lblUsageText {
            get {
                return ResourceManager.GetString("FrmHelp_lblUsageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Cancel ähnelt.
        /// </summary>
        internal static string FrmLogin_btnCancel {
            get {
                return ResourceManager.GetString("FrmLogin_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;OK ähnelt.
        /// </summary>
        internal static string FrmLogin_btnOK {
            get {
                return ResourceManager.GetString("FrmLogin_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your password. ähnelt.
        /// </summary>
        internal static string FrmLogin_Error_Password_Text {
            get {
                return ResourceManager.GetString("FrmLogin_Error_Password_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No password entered ähnelt.
        /// </summary>
        internal static string FrmLogin_Error_Passwort_Title {
            get {
                return ResourceManager.GetString("FrmLogin_Error_Passwort_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your username. ähnelt.
        /// </summary>
        internal static string FrmLogin_Error_Username_Text {
            get {
                return ResourceManager.GetString("FrmLogin_Error_Username_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No username entered ähnelt.
        /// </summary>
        internal static string FrmLogin_Error_Username_Title {
            get {
                return ResourceManager.GetString("FrmLogin_Error_Username_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login Data ähnelt.
        /// </summary>
        internal static string FrmLogin_lblHeader {
            get {
                return ResourceManager.GetString("FrmLogin_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your login data for OTR to continue your action. ähnelt.
        /// </summary>
        internal static string FrmLogin_lblLoginIntroduction {
            get {
                return ResourceManager.GetString("FrmLogin_lblLoginIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Password: ähnelt.
        /// </summary>
        internal static string FrmLogin_lblPassword {
            get {
                return ResourceManager.GetString("FrmLogin_lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Timezone: ähnelt.
        /// </summary>
        internal static string FrmLogin_lblTimezone {
            get {
                return ResourceManager.GetString("FrmLogin_lblTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Username: ähnelt.
        /// </summary>
        internal static string FrmLogin_lblUsername {
            get {
                return ResourceManager.GetString("FrmLogin_lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login to OTR ähnelt.
        /// </summary>
        internal static string FrmLogin_Title {
            get {
                return ResourceManager.GetString("FrmLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Cancel ähnelt.
        /// </summary>
        internal static string FrmMain_btnCancel {
            get {
                return ResourceManager.GetString("FrmMain_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Help ähnelt.
        /// </summary>
        internal static string FrmMain_btnHelp {
            get {
                return ResourceManager.GetString("FrmMain_btnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;OK ähnelt.
        /// </summary>
        internal static string FrmMain_btnOK {
            get {
                return ResourceManager.GetString("FrmMain_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die P&amp;references ähnelt.
        /// </summary>
        internal static string FrmMain_btnPreferences {
            get {
                return ResourceManager.GetString("FrmMain_btnPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None active... ähnelt.
        /// </summary>
        internal static string FrmMain_Error_NoPlugin {
            get {
                return ResourceManager.GetString("FrmMain_Error_NoPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You did not enter an OTR password. If the username and/or password fields are empty,
        ///you have to enter the data each time you want to record a TV show.
        ///
        ///Do you really want this? ähnelt.
        /// </summary>
        internal static string FrmMain_Error_Password_Text {
            get {
                return ResourceManager.GetString("FrmMain_Error_Password_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No password entered ähnelt.
        /// </summary>
        internal static string FrmMain_Error_Password_Title {
            get {
                return ResourceManager.GetString("FrmMain_Error_Password_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured while the plugin applied the changes: {0} ähnelt.
        /// </summary>
        internal static string FrmMain_Error_Plugin_Text {
            get {
                return ResourceManager.GetString("FrmMain_Error_Plugin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while saving changes ähnelt.
        /// </summary>
        internal static string FrmMain_Error_Plugin_Title {
            get {
                return ResourceManager.GetString("FrmMain_Error_Plugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The plugin returned an unexpected result while applying the changes. Please contact the plugin&apos;s manufacturer for further help.
        ///
        ///The result was: {0} ähnelt.
        /// </summary>
        internal static string FrmMain_Error_PluginResult_Text {
            get {
                return ResourceManager.GetString("FrmMain_Error_PluginResult_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin returned unexpected result ähnelt.
        /// </summary>
        internal static string FrmMain_Error_PluginResult_Title {
            get {
                return ResourceManager.GetString("FrmMain_Error_PluginResult_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You did not enter an OTR username. If the username and/or password fields are empty,
        ///you have to enter the data each time you want to record a TV show.
        ///
        ///Do you really want this? ähnelt.
        /// </summary>
        internal static string FrmMain_Error_Username_Text {
            get {
                return ResourceManager.GetString("FrmMain_Error_Username_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No username entered ähnelt.
        /// </summary>
        internal static string FrmMain_Error_Username_Title {
            get {
                return ResourceManager.GetString("FrmMain_Error_Username_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recording Settings ähnelt.
        /// </summary>
        internal static string FrmMain_gbRecording {
            get {
                return ResourceManager.GetString("FrmMain_gbRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin Settings ähnelt.
        /// </summary>
        internal static string FrmMain_gbTVGuide {
            get {
                return ResourceManager.GetString("FrmMain_gbTVGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your user data at OnlineTVRecorder.com ähnelt.
        /// </summary>
        internal static string FrmMain_gbUserdata {
            get {
                return ResourceManager.GetString("FrmMain_gbUserdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help_en.chm ähnelt.
        /// </summary>
        internal static string FrmMain_HelpFilename {
            get {
                return ResourceManager.GetString("FrmMain_HelpFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Control Panel ähnelt.
        /// </summary>
        internal static string FrmMain_lblHeader {
            get {
                return ResourceManager.GetString("FrmMain_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to OTR Remote! Please configure the basic data for running the software.
        ///Note: Adding and removing of TV shows is done via the commandline interface. ähnelt.
        /// </summary>
        internal static string FrmMain_lblIntroduction {
            get {
                return ResourceManager.GetString("FrmMain_lblIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Password: ähnelt.
        /// </summary>
        internal static string FrmMain_lblPassword {
            get {
                return ResourceManager.GetString("FrmMain_lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Timezone: ähnelt.
        /// </summary>
        internal static string FrmMain_lblTimezone {
            get {
                return ResourceManager.GetString("FrmMain_lblTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TV &amp;Guide Plugin: ähnelt.
        /// </summary>
        internal static string FrmMain_lblTVGuide {
            get {
                return ResourceManager.GetString("FrmMain_lblTVGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Username: ähnelt.
        /// </summary>
        internal static string FrmMain_lblUsername {
            get {
                return ResourceManager.GetString("FrmMain_lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setting ähnelt.
        /// </summary>
        internal static string FrmMain_lvSettings_Setting {
            get {
                return ResourceManager.GetString("FrmMain_lvSettings_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        internal static string FrmMain_lvSettings_Value {
            get {
                return ResourceManager.GetString("FrmMain_lvSettings_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quits the application without saving any changes. ähnelt.
        /// </summary>
        internal static string FrmMain_Tooltip_Cancel {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opens OTR Remote&apos;s help files. ähnelt.
        /// </summary>
        internal static string FrmMain_Tooltip_Help {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saves the changes you made and quits the application. ähnelt.
        /// </summary>
        internal static string FrmMain_Tooltip_OK {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is your OTR password. ähnelt.
        /// </summary>
        internal static string FrmMain_Tooltip_Password {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customize the behavior of OTR Remote,
        ///edit network and proxy settings,
        ///look for new program versions and
        ///show informations about this application. ähnelt.
        /// </summary>
        internal static string FrmMain_Tooltip_Preferences {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Defines the global timezone you are located in.
        ///This setting helps OTR to indicate the correct recording times. ähnelt.
        /// </summary>
        internal static string FrmMain_Tooltip_Timezone {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Context Sensitive Help ähnelt.
        /// </summary>
        internal static string FrmMain_Tooltip_Title {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the TV Guide Plugin you want to use with OTR Remote.
        ///Please note that although a program may not be listed here, you can still setup it manually.
        ///In such case, please read the application&apos;s manual. ähnelt.
        /// </summary>
        internal static string FrmMain_Tooltip_TVGuide {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_TVGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is your OTR username or e-mail address. ähnelt.
        /// </summary>
        internal static string FrmMain_Tooltip_Username {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string FrmMain_Value_BoolNo {
            get {
                return ResourceManager.GetString("FrmMain_Value_BoolNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string FrmMain_Value_BoolYes {
            get {
                return ResourceManager.GetString("FrmMain_Value_BoolYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Cancel ähnelt.
        /// </summary>
        internal static string FrmPreferences_btnCancel {
            get {
                return ResourceManager.GetString("FrmPreferences_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E&amp;dit Station Corrections... ähnelt.
        /// </summary>
        internal static string FrmPreferences_btnEditStations {
            get {
                return ResourceManager.GetString("FrmPreferences_btnEditStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;OK ähnelt.
        /// </summary>
        internal static string FrmPreferences_btnOK {
            get {
                return ResourceManager.GetString("FrmPreferences_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Record shows, which already begun ähnelt.
        /// </summary>
        internal static string FrmPreferences_cbAdjustStartTime {
            get {
                return ResourceManager.GetString("FrmPreferences_cbAdjustStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hi&amp;de indicator after: ähnelt.
        /// </summary>
        internal static string FrmPreferences_cbAutoClose {
            get {
                return ResourceManager.GetString("FrmPreferences_cbAutoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically check for updates &amp;weekly ähnelt.
        /// </summary>
        internal static string FrmPreferences_cbAutoUpdate {
            get {
                return ResourceManager.GetString("FrmPreferences_cbAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide ähnelt.
        /// </summary>
        internal static string FrmPreferences_cbProgressMethod_Hide {
            get {
                return ResourceManager.GetString("FrmPreferences_cbProgressMethod_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Systray Icon ähnelt.
        /// </summary>
        internal static string FrmPreferences_cbProgressMethod_ShowSystrayIcon {
            get {
                return ResourceManager.GetString("FrmPreferences_cbProgressMethod_ShowSystrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Window ähnelt.
        /// </summary>
        internal static string FrmPreferences_cbProgressMethod_ShowWindow {
            get {
                return ResourceManager.GetString("FrmPreferences_cbProgressMethod_ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Use proxy server ähnelt.
        /// </summary>
        internal static string FrmPreferences_cbProxy {
            get {
                return ResourceManager.GetString("FrmPreferences_cbProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aut&amp;hentication is required: ähnelt.
        /// </summary>
        internal static string FrmPreferences_cbProxyAuthentication {
            get {
                return ResourceManager.GetString("FrmPreferences_cbProxyAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Non-default authentication is required: ähnelt.
        /// </summary>
        internal static string FrmPreferences_cbProxyAuthenticationIE {
            get {
                return ResourceManager.GetString("FrmPreferences_cbProxyAuthenticationIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Also record following show ähnelt.
        /// </summary>
        internal static string FrmPreferences_cbRecordFollowing {
            get {
                return ResourceManager.GetString("FrmPreferences_cbRecordFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto&amp;matically retry recording deletion ähnelt.
        /// </summary>
        internal static string FrmPreferences_cbRetryDelete {
            get {
                return ResourceManager.GetString("FrmPreferences_cbRetryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crazysoft AppUpdate was not found. Please install the program before trying to update. ähnelt.
        /// </summary>
        internal static string FrmPreferences_Error_AppUpdate_Text {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_AppUpdate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program not found ähnelt.
        /// </summary>
        internal static string FrmPreferences_Error_AppUpdate_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_AppUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The proxy port must be a number between 0 and 65535. ähnelt.
        /// </summary>
        internal static string FrmPreferences_Error_PortWrong_Text {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_PortWrong_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrong proxy port entered ähnelt.
        /// </summary>
        internal static string FrmPreferences_Error_PortWrong_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_PortWrong_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a proxy address. ähnelt.
        /// </summary>
        internal static string FrmPreferences_Error_ProxyAddress_Text {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_ProxyAddress_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No proxy address entered ähnelt.
        /// </summary>
        internal static string FrmPreferences_Error_ProxyAddress_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_ProxyAddress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a proxy port. ähnelt.
        /// </summary>
        internal static string FrmPreferences_Error_ProxyPort_Text {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_ProxyPort_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No proxy port entered ähnelt.
        /// </summary>
        internal static string FrmPreferences_Error_ProxyPort_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_ProxyPort_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a proxy username. ähnelt.
        /// </summary>
        internal static string FrmPreferences_Error_ProxyUser_Text {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_ProxyUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No proxy username entered ähnelt.
        /// </summary>
        internal static string FrmPreferences_Error_ProxyUser_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_ProxyUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crazysoft AppUpdate could not be started. Please check the program location or reinstall the application.
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string FrmPreferences_Error_Update_Text {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_Update_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not start program ähnelt.
        /// </summary>
        internal static string FrmPreferences_Error_Update_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright {0}. All rights reserved. ähnelt.
        /// </summary>
        internal static string FrmPreferences_lblCopyright {
            get {
                return ResourceManager.GetString("FrmPreferences_lblCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last update check: {0} ähnelt.
        /// </summary>
        internal static string FrmPreferences_lblLastUpdate {
            get {
                return ResourceManager.GetString("FrmPreferences_lblLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die never ähnelt.
        /// </summary>
        internal static string FrmPreferences_lblLastUpdate_Never {
            get {
                return ResourceManager.GetString("FrmPreferences_lblLastUpdate_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Progre&amp;ss Indicator: ähnelt.
        /// </summary>
        internal static string FrmPreferences_lblProgressIndicator {
            get {
                return ResourceManager.GetString("FrmPreferences_lblProgressIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Address: ähnelt.
        /// </summary>
        internal static string FrmPreferences_lblProxyAddress {
            get {
                return ResourceManager.GetString("FrmPreferences_lblProxyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwor&amp;d: ähnelt.
        /// </summary>
        internal static string FrmPreferences_lblProxyPassword {
            get {
                return ResourceManager.GetString("FrmPreferences_lblProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Po&amp;rt: ähnelt.
        /// </summary>
        internal static string FrmPreferences_lblProxyPort {
            get {
                return ResourceManager.GetString("FrmPreferences_lblProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Us&amp;ername: ähnelt.
        /// </summary>
        internal static string FrmPreferences_lblProxyUser {
            get {
                return ResourceManager.GetString("FrmPreferences_lblProxyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die seconds ähnelt.
        /// </summary>
        internal static string FrmPreferences_lblSeconds {
            get {
                return ResourceManager.GetString("FrmPreferences_lblSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thanks to the folks at OnlineTVRecorder.com for their great service.
        ///Thanks to the community at CodeProject.com for their coding help. ähnelt.
        /// </summary>
        internal static string FrmPreferences_lblThanks {
            get {
                return ResourceManager.GetString("FrmPreferences_lblThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version {0} ähnelt.
        /// </summary>
        internal static string FrmPreferences_lblVersion {
            get {
                return ResourceManager.GetString("FrmPreferences_lblVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for updates... ähnelt.
        /// </summary>
        internal static string FrmPreferences_llblUpdate {
            get {
                return ResourceManager.GetString("FrmPreferences_llblUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OTR Remote has to be closed before updating it. Any unsaved work will be lost. Do you want to exit the application now? ähnelt.
        /// </summary>
        internal static string FrmPreferences_Msg_AppUpdate_Text {
            get {
                return ResourceManager.GetString("FrmPreferences_Msg_AppUpdate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quitting required ähnelt.
        /// </summary>
        internal static string FrmPreferences_Msg_AppUpdate_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Msg_AppUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use custom pro&amp;xy: ähnelt.
        /// </summary>
        internal static string FrmPreferences_rbCustomProxy {
            get {
                return ResourceManager.GetString("FrmPreferences_rbCustomProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use IE &amp;default proxy settings ähnelt.
        /// </summary>
        internal static string FrmPreferences_rbDefaultProxy {
            get {
                return ResourceManager.GetString("FrmPreferences_rbDefaultProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string FrmPreferences_Tab_About {
            get {
                return ResourceManager.GetString("FrmPreferences_Tab_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Network ähnelt.
        /// </summary>
        internal static string FrmPreferences_Tab_Network {
            get {
                return ResourceManager.GetString("FrmPreferences_Tab_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program ähnelt.
        /// </summary>
        internal static string FrmPreferences_Tab_Program {
            get {
                return ResourceManager.GetString("FrmPreferences_Tab_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program Preferences ähnelt.
        /// </summary>
        internal static string FrmPreferences_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Cancel ähnelt.
        /// </summary>
        internal static string FrmProgress_btnClose {
            get {
                return ResourceManager.GetString("FrmProgress_btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Close ({0}) ähnelt.
        /// </summary>
        internal static string FrmProgress_btnClose_Countdown {
            get {
                return ResourceManager.GetString("FrmProgress_btnClose_Countdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The start date respectively the start time have to be in future. Please check them. ähnelt.
        /// </summary>
        internal static string FrmProgress_Error_Date {
            get {
                return ResourceManager.GetString("FrmProgress_Error_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OTR Remote has stumbled over an unknown status message. The file {0} has been saved. Please check the recording status manually and send the file to the Crazysoft support to allow an error fix. ähnelt.
        /// </summary>
        internal static string FrmProgress_Error_ParseError {
            get {
                return ResourceManager.GetString("FrmProgress_Error_ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The login data you provided is not correct. Please check it. ähnelt.
        /// </summary>
        internal static string FrmProgress_Error_WrongLogin {
            get {
                return ResourceManager.GetString("FrmProgress_Error_WrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A connection error occured while trying to modify your recording:
        ///
        ///{0}
        ///
        ///Please check your network and proxy settings. ähnelt.
        /// </summary>
        internal static string FrmProgress_ErrorMsg_ConnErr_Text {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_ConnErr_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection Error ähnelt.
        /// </summary>
        internal static string FrmProgress_ErrorMsg_ConnErr_Title {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_ConnErr_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The recording could not be deleted. Please check if you really have it in your recording list and username and password are correct. ähnelt.
        /// </summary>
        internal static string FrmProgress_ErrorMsg_DeleteError_Text {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_DeleteError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deletion Error ähnelt.
        /// </summary>
        internal static string FrmProgress_ErrorMsg_DeleteError_Title {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_DeleteError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The EPG ID for the recording could not be found. Probably, the OTR EPG has a different title for the recording than your EPG or it is too far in future.
        ///Please delete the recording on the OTR website. ähnelt.
        /// </summary>
        internal static string FrmProgress_ErrorMsg_EPGNotFound_Text {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_EPGNotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EPG ID not found ähnelt.
        /// </summary>
        internal static string FrmProgress_ErrorMsg_EPGNotFound_Title {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_EPGNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OTR needs some time before recently added recordings are deletable. If you are sure that this recording is in your recording list, you should try deleting it again in a few minutes.
        ///
        ///Should OTR Remote retry to delete this recording automatically in 10 minutes? ähnelt.
        /// </summary>
        internal static string FrmProgress_ErrorMsg_NotRecorded {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_NotRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recording Error ähnelt.
        /// </summary>
        internal static string FrmProgress_ErrorMsg_Title {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please wait, while OTR Remote modifies the recording. ähnelt.
        /// </summary>
        internal static string FrmProgress_lblDescription {
            get {
                return ResourceManager.GetString("FrmProgress_lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action Progress ähnelt.
        /// </summary>
        internal static string FrmProgress_lblHeader {
            get {
                return ResourceManager.GetString("FrmProgress_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;b&gt;You are not allowed to delete this recording!&lt;/b&gt; ähnelt.
        /// </summary>
        internal static string FrmProgress_Result_NotRecorded {
            get {
                return ResourceManager.GetString("FrmProgress_Result_NotRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;b&gt;Recording job has been created&lt;/b&gt; ähnelt.
        /// </summary>
        internal static string FrmProgress_Result_Success {
            get {
                return ResourceManager.GetString("FrmProgress_Result_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;b&gt;Error:&lt;/b&gt; This show has already begun! ähnelt.
        /// </summary>
        internal static string FrmProgress_Result_TooLate {
            get {
                return ResourceManager.GetString("FrmProgress_Result_TooLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Um diesen Service nutzen zu k�nnen, m�ssen Sie eingeloggt sein. ähnelt.
        /// </summary>
        internal static string FrmProgress_Result_WrongLogin {
            get {
                return ResourceManager.GetString("FrmProgress_Result_WrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please wait, aborting... ähnelt.
        /// </summary>
        internal static string FrmProgress_Status_Aborting {
            get {
                return ResourceManager.GetString("FrmProgress_Status_Aborting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting for retry of deletion in {0}... ähnelt.
        /// </summary>
        internal static string FrmProgress_Status_DeletionDeferred {
            get {
                return ResourceManager.GetString("FrmProgress_Status_DeletionDeferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action aborted: An error has occured. ähnelt.
        /// </summary>
        internal static string FrmProgress_Status_Error {
            get {
                return ResourceManager.GetString("FrmProgress_Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The action was successfully finished. ähnelt.
        /// </summary>
        internal static string FrmProgress_Status_Finished {
            get {
                return ResourceManager.GetString("FrmProgress_Status_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking IE default proxy settings... ähnelt.
        /// </summary>
        internal static string FrmProgress_Status_Proxy {
            get {
                return ResourceManager.GetString("FrmProgress_Status_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Searching EPG ID of recording... ähnelt.
        /// </summary>
        internal static string FrmProgress_Status_SearchingEPG {
            get {
                return ResourceManager.GetString("FrmProgress_Status_SearchingEPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sending the recording job to OTR... ähnelt.
        /// </summary>
        internal static string FrmProgress_Status_Sending {
            get {
                return ResourceManager.GetString("FrmProgress_Status_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unfortunately, OTR Remote could not delete your recording again. ähnelt.
        /// </summary>
        internal static string FrmProgress_Systray_Deletion_Error {
            get {
                return ResourceManager.GetString("FrmProgress_Systray_Deletion_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OTR Remote will stay in your System Tray and try deleting your recording again in 10 minutes. ähnelt.
        /// </summary>
        internal static string FrmProgress_Systray_Deletion_Intro {
            get {
                return ResourceManager.GetString("FrmProgress_Systray_Deletion_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OTR Remote has successfully deleted your recording. ähnelt.
        /// </summary>
        internal static string FrmProgress_Systray_Deletion_Success {
            get {
                return ResourceManager.GetString("FrmProgress_Systray_Deletion_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OTR Remote (retry in {0}) ähnelt.
        /// </summary>
        internal static string FrmProgress_Systray_Deletion_Timer {
            get {
                return ResourceManager.GetString("FrmProgress_Systray_Deletion_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deletion Deferred ähnelt.
        /// </summary>
        internal static string FrmProgress_Systray_Deletion_Title {
            get {
                return ResourceManager.GetString("FrmProgress_Systray_Deletion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You don&apos;t have read and/or write access to the Station Correction file. Saving of changes is disabled. ähnelt.
        /// </summary>
        internal static string FrmStations_AccessMsg_Text {
            get {
                return ResourceManager.GetString("FrmStations_AccessMsg_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving disabled ähnelt.
        /// </summary>
        internal static string FrmStations_AccessMsg_Title {
            get {
                return ResourceManager.GetString("FrmStations_AccessMsg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Cancel ähnelt.
        /// </summary>
        internal static string FrmStations_btnCancel {
            get {
                return ResourceManager.GetString("FrmStations_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A&amp;dd ähnelt.
        /// </summary>
        internal static string FrmStations_btnEPGAdd {
            get {
                return ResourceManager.GetString("FrmStations_btnEPGAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cha&amp;nge ähnelt.
        /// </summary>
        internal static string FrmStations_btnEPGChange {
            get {
                return ResourceManager.GetString("FrmStations_btnEPGChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die R&amp;emove ähnelt.
        /// </summary>
        internal static string FrmStations_btnEPGRemove {
            get {
                return ResourceManager.GetString("FrmStations_btnEPGRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;OK ähnelt.
        /// </summary>
        internal static string FrmStations_btnOK {
            get {
                return ResourceManager.GetString("FrmStations_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Add ähnelt.
        /// </summary>
        internal static string FrmStations_btnOTRAdd {
            get {
                return ResourceManager.GetString("FrmStations_btnOTRAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C&amp;hange ähnelt.
        /// </summary>
        internal static string FrmStations_btnOTRChange {
            get {
                return ResourceManager.GetString("FrmStations_btnOTRChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Remove ähnelt.
        /// </summary>
        internal static string FrmStations_btnOTRRemove {
            get {
                return ResourceManager.GetString("FrmStations_btnOTRRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Case-&amp;sensitive station name replacements ähnelt.
        /// </summary>
        internal static string FrmStations_cbCaseSensitive {
            get {
                return ResourceManager.GetString("FrmStations_cbCaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced Settings ähnelt.
        /// </summary>
        internal static string FrmStations_gbAdvanced {
            get {
                return ResourceManager.GetString("FrmStations_gbAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every EPG software has its own name for TV stations. To make sure OTR gets the correct station name, enter the replacements here. ähnelt.
        /// </summary>
        internal static string FrmStations_lblDescription {
            get {
                return ResourceManager.GetString("FrmStations_lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EPG Station Replacements: ähnelt.
        /// </summary>
        internal static string FrmStations_lblEPGStation {
            get {
                return ResourceManager.GetString("FrmStations_lblEPGStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OTR Station Names: ähnelt.
        /// </summary>
        internal static string FrmStations_lblOTRStation {
            get {
                return ResourceManager.GetString("FrmStations_lblOTRStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured while trying to save the changes. Please check the file permissions and try again. ähnelt.
        /// </summary>
        internal static string FrmStations_SaveMsg_Text {
            get {
                return ResourceManager.GetString("FrmStations_SaveMsg_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while saving changes ähnelt.
        /// </summary>
        internal static string FrmStations_SaveMsg_Title {
            get {
                return ResourceManager.GetString("FrmStations_SaveMsg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Station Corrections ähnelt.
        /// </summary>
        internal static string FrmStations_Title {
            get {
                return ResourceManager.GetString("FrmStations_Title", resourceCulture);
            }
        }
    }
}
