//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazysoft.OTRRemote.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OTRRemote {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OTRRemote() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crazysoft.OTRRemote.Lang.OTRRemote", typeof(OTRRemote).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete {0} from {1} at {2}? If you delete the recording, it will not be recorded, or you will not be able to decode it..
        /// </summary>
        internal static string CmdLine_DeleteMsg_Text {
            get {
                return ResourceManager.GetString("CmdLine_DeleteMsg_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this show.
        /// </summary>
        internal static string CmdLine_DeleteMsg_ThisShow {
            get {
                return ResourceManager.GetString("CmdLine_DeleteMsg_ThisShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        internal static string CmdLine_DeleteMsg_Title {
            get {
                return ResourceManager.GetString("CmdLine_DeleteMsg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action set (-a for Add, -r for Remove).
        /// </summary>
        internal static string CmdLine_Error_Action {
            get {
                return ResourceManager.GetString("CmdLine_Error_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No end time set or wrong format (-et=hh:mm; e.g.: -et=22:05).
        /// </summary>
        internal static string CmdLine_Error_EndTime {
            get {
                return ResourceManager.GetString("CmdLine_Error_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No start date set or wrong format (-sd=yyyy-mm-dd; e.g.: -sd=2006-04-13).
        /// </summary>
        internal static string CmdLine_Error_StartDate {
            get {
                return ResourceManager.GetString("CmdLine_Error_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No start time set or wrong format (-st=hh:mm; e.g.: -st=20:15).
        /// </summary>
        internal static string CmdLine_Error_StartTime {
            get {
                return ResourceManager.GetString("CmdLine_Error_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No station set (-s=&quot;Station Name&quot;).
        /// </summary>
        internal static string CmdLine_Error_Station {
            get {
                return ResourceManager.GetString("CmdLine_Error_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors while trying to add a recording:
        ///
        ///{0}
        ///Would you like to read the Recording Help?.
        /// </summary>
        internal static string CmdLine_ErrorMsg_Text {
            get {
                return ResourceManager.GetString("CmdLine_ErrorMsg_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Error.
        /// </summary>
        internal static string CmdLine_ErrorMsg_Title {
            get {
                return ResourceManager.GetString("CmdLine_ErrorMsg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string FrmHelp_btnClose {
            get {
                return ResourceManager.GetString("FrmHelp_btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commandline Arguments:.
        /// </summary>
        internal static string FrmHelp_lblCmdArgsHeader {
            get {
                return ResourceManager.GetString("FrmHelp_lblCmdArgsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -a Add a recording.
        ///-r Remove a recording.
        ///-h Show this help.
        ///-s Short name of the TV station to record.
        ///-sd Start date of the recording. (Format: yyyy-mm-dd)
        ///-st Start time of the recording. (Format: hh:mm)
        ///-et End time of the recording. (Format: hh:mm).
        /// </summary>
        internal static string FrmHelp_lblCmdArgsText {
            get {
                return ResourceManager.GetString("FrmHelp_lblCmdArgsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Help.
        /// </summary>
        internal static string FrmHelp_lblHeader {
            get {
                return ResourceManager.GetString("FrmHelp_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string FrmHelp_lblNotesHeader {
            get {
                return ResourceManager.GetString("FrmHelp_lblNotesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an argument is shown within quotation marks, you have to write them too!
        ///Username, password and timezone don&apos;t have to be set if you configured them in the Control Panel..
        /// </summary>
        internal static string FrmHelp_lblNotesText {
            get {
                return ResourceManager.GetString("FrmHelp_lblNotesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Arguments:.
        /// </summary>
        internal static string FrmHelp_lblOptionalArgsHeader {
            get {
                return ResourceManager.GetString("FrmHelp_lblOptionalArgsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -t Title of the TV show to record.
        ///-g Genre of the TV show.
        ///-u Your OTR username or e-mail address.
        ///-p Your OTR password.
        ///-tz Timezone: The difference to GMT in hours. (e.g. Middle Europe: 1).
        /// </summary>
        internal static string FrmHelp_lblOptionalArgsText {
            get {
                return ResourceManager.GetString("FrmHelp_lblOptionalArgsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string FrmHelp_lblUsageHeader {
            get {
                return ResourceManager.GetString("FrmHelp_lblUsageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTRRemote.exe -a|-r -s=&quot;Station&quot; -sd=yyyy-mm-dd -st=hh:mm -et=hh:mm [-t=&quot;Title&quot;] [-u=&quot;User&quot;] [-p=&quot;Password&quot;] [-tz=Timezone].
        /// </summary>
        internal static string FrmHelp_lblUsageText {
            get {
                return ResourceManager.GetString("FrmHelp_lblUsageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string FrmLogin_btnCancel {
            get {
                return ResourceManager.GetString("FrmLogin_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string FrmLogin_btnOK {
            get {
                return ResourceManager.GetString("FrmLogin_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password..
        /// </summary>
        internal static string FrmLogin_Error_Password_Text {
            get {
                return ResourceManager.GetString("FrmLogin_Error_Password_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password entered.
        /// </summary>
        internal static string FrmLogin_Error_Passwort_Title {
            get {
                return ResourceManager.GetString("FrmLogin_Error_Passwort_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username..
        /// </summary>
        internal static string FrmLogin_Error_Username_Text {
            get {
                return ResourceManager.GetString("FrmLogin_Error_Username_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No username entered.
        /// </summary>
        internal static string FrmLogin_Error_Username_Title {
            get {
                return ResourceManager.GetString("FrmLogin_Error_Username_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Data.
        /// </summary>
        internal static string FrmLogin_lblHeader {
            get {
                return ResourceManager.GetString("FrmLogin_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your login data for OTR to continue your action..
        /// </summary>
        internal static string FrmLogin_lblLoginIntroduction {
            get {
                return ResourceManager.GetString("FrmLogin_lblLoginIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Password:.
        /// </summary>
        internal static string FrmLogin_lblPassword {
            get {
                return ResourceManager.GetString("FrmLogin_lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Timezone:.
        /// </summary>
        internal static string FrmLogin_lblTimezone {
            get {
                return ResourceManager.GetString("FrmLogin_lblTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Username:.
        /// </summary>
        internal static string FrmLogin_lblUsername {
            get {
                return ResourceManager.GetString("FrmLogin_lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to OTR.
        /// </summary>
        internal static string FrmLogin_Title {
            get {
                return ResourceManager.GetString("FrmLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string FrmMain_btnCancel {
            get {
                return ResourceManager.GetString("FrmMain_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string FrmMain_btnHelp {
            get {
                return ResourceManager.GetString("FrmMain_btnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string FrmMain_btnOK {
            get {
                return ResourceManager.GetString("FrmMain_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;references.
        /// </summary>
        internal static string FrmMain_btnPreferences {
            get {
                return ResourceManager.GetString("FrmMain_btnPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None active....
        /// </summary>
        internal static string FrmMain_Error_NoPlugin {
            get {
                return ResourceManager.GetString("FrmMain_Error_NoPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not enter an OTR password. If the username and/or password fields are empty,
        ///you have to enter the data each time you want to record a TV show.
        ///
        ///Do you really want this?.
        /// </summary>
        internal static string FrmMain_Error_Password_Text {
            get {
                return ResourceManager.GetString("FrmMain_Error_Password_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password entered.
        /// </summary>
        internal static string FrmMain_Error_Password_Title {
            get {
                return ResourceManager.GetString("FrmMain_Error_Password_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while the plugin applied the changes: {0}.
        /// </summary>
        internal static string FrmMain_Error_Plugin_Text {
            get {
                return ResourceManager.GetString("FrmMain_Error_Plugin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving changes.
        /// </summary>
        internal static string FrmMain_Error_Plugin_Title {
            get {
                return ResourceManager.GetString("FrmMain_Error_Plugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin returned an unexpected result while applying the changes. Please contact the plugin&apos;s manufacturer for further help.
        ///
        ///The result was: {0}.
        /// </summary>
        internal static string FrmMain_Error_PluginResult_Text {
            get {
                return ResourceManager.GetString("FrmMain_Error_PluginResult_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin returned unexpected result.
        /// </summary>
        internal static string FrmMain_Error_PluginResult_Title {
            get {
                return ResourceManager.GetString("FrmMain_Error_PluginResult_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not enter an OTR username. If the username and/or password fields are empty,
        ///you have to enter the data each time you want to record a TV show.
        ///
        ///Do you really want this?.
        /// </summary>
        internal static string FrmMain_Error_Username_Text {
            get {
                return ResourceManager.GetString("FrmMain_Error_Username_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No username entered.
        /// </summary>
        internal static string FrmMain_Error_Username_Title {
            get {
                return ResourceManager.GetString("FrmMain_Error_Username_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Settings.
        /// </summary>
        internal static string FrmMain_gbRecording {
            get {
                return ResourceManager.GetString("FrmMain_gbRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Settings.
        /// </summary>
        internal static string FrmMain_gbTVGuide {
            get {
                return ResourceManager.GetString("FrmMain_gbTVGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user data at OnlineTVRecorder.com.
        /// </summary>
        internal static string FrmMain_gbUserdata {
            get {
                return ResourceManager.GetString("FrmMain_gbUserdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help_en.chm.
        /// </summary>
        internal static string FrmMain_HelpFilename {
            get {
                return ResourceManager.GetString("FrmMain_HelpFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        internal static string FrmMain_lblHeader {
            get {
                return ResourceManager.GetString("FrmMain_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to OTR Remote! Please configure the basic data for running the software.
        ///Note: Adding and removing of TV shows is done via the commandline interface..
        /// </summary>
        internal static string FrmMain_lblIntroduction {
            get {
                return ResourceManager.GetString("FrmMain_lblIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Password:.
        /// </summary>
        internal static string FrmMain_lblPassword {
            get {
                return ResourceManager.GetString("FrmMain_lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Timezone:.
        /// </summary>
        internal static string FrmMain_lblTimezone {
            get {
                return ResourceManager.GetString("FrmMain_lblTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV &amp;Guide Application:.
        /// </summary>
        internal static string FrmMain_lblTVGuide {
            get {
                return ResourceManager.GetString("FrmMain_lblTVGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Username:.
        /// </summary>
        internal static string FrmMain_lblUsername {
            get {
                return ResourceManager.GetString("FrmMain_lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string FrmMain_lvSettings_Setting {
            get {
                return ResourceManager.GetString("FrmMain_lvSettings_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string FrmMain_lvSettings_Value {
            get {
                return ResourceManager.GetString("FrmMain_lvSettings_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quits the application without saving any changes..
        /// </summary>
        internal static string FrmMain_Tooltip_Cancel {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens OTR Remote&apos;s help files..
        /// </summary>
        internal static string FrmMain_Tooltip_Help {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the changes you made and quits the application..
        /// </summary>
        internal static string FrmMain_Tooltip_OK {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your OTR password..
        /// </summary>
        internal static string FrmMain_Tooltip_Password {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize the behavior of OTR Remote,
        ///edit network and proxy settings,
        ///look for new program versions and
        ///show informations about this application..
        /// </summary>
        internal static string FrmMain_Tooltip_Preferences {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the global timezone you are located in.
        ///This setting helps OTR to indicate the correct recording times..
        /// </summary>
        internal static string FrmMain_Tooltip_Timezone {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Sensitive Help.
        /// </summary>
        internal static string FrmMain_Tooltip_Title {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the TV Guide Plugin you want to use with OTR Remote.
        ///Please note that although a program may not be listed here, you can still setup it manually.
        ///In such case, please read the application&apos;s manual..
        /// </summary>
        internal static string FrmMain_Tooltip_TVGuide {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_TVGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your OTR username or e-mail address..
        /// </summary>
        internal static string FrmMain_Tooltip_Username {
            get {
                return ResourceManager.GetString("FrmMain_Tooltip_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string FrmMain_Value_BoolNo {
            get {
                return ResourceManager.GetString("FrmMain_Value_BoolNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string FrmMain_Value_BoolYes {
            get {
                return ResourceManager.GetString("FrmMain_Value_BoolYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string FrmPreferences_btnCancel {
            get {
                return ResourceManager.GetString("FrmPreferences_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;dit Station Corrections....
        /// </summary>
        internal static string FrmPreferences_btnEditStations {
            get {
                return ResourceManager.GetString("FrmPreferences_btnEditStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string FrmPreferences_btnOK {
            get {
                return ResourceManager.GetString("FrmPreferences_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record shows, which already begun.
        /// </summary>
        internal static string FrmPreferences_cbAdjustStartTime {
            get {
                return ResourceManager.GetString("FrmPreferences_cbAdjustStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi&amp;de indicator after:.
        /// </summary>
        internal static string FrmPreferences_cbAutoClose {
            get {
                return ResourceManager.GetString("FrmPreferences_cbAutoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check for updates &amp;weekly.
        /// </summary>
        internal static string FrmPreferences_cbAutoUpdate {
            get {
                return ResourceManager.GetString("FrmPreferences_cbAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string FrmPreferences_cbProgressMethod_Hide {
            get {
                return ResourceManager.GetString("FrmPreferences_cbProgressMethod_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Systray Icon.
        /// </summary>
        internal static string FrmPreferences_cbProgressMethod_ShowSystrayIcon {
            get {
                return ResourceManager.GetString("FrmPreferences_cbProgressMethod_ShowSystrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Window.
        /// </summary>
        internal static string FrmPreferences_cbProgressMethod_ShowWindow {
            get {
                return ResourceManager.GetString("FrmPreferences_cbProgressMethod_ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Use proxy server.
        /// </summary>
        internal static string FrmPreferences_cbProxy {
            get {
                return ResourceManager.GetString("FrmPreferences_cbProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aut&amp;hentication is required:.
        /// </summary>
        internal static string FrmPreferences_cbProxyAuthentication {
            get {
                return ResourceManager.GetString("FrmPreferences_cbProxyAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Non-default authentication is required:.
        /// </summary>
        internal static string FrmPreferences_cbProxyAuthenticationIE {
            get {
                return ResourceManager.GetString("FrmPreferences_cbProxyAuthenticationIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also record following show.
        /// </summary>
        internal static string FrmPreferences_cbRecordFollowing {
            get {
                return ResourceManager.GetString("FrmPreferences_cbRecordFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show recording &amp;preview before sending job.
        /// </summary>
        internal static string FrmPreferences_cbRecordingPreview {
            get {
                return ResourceManager.GetString("FrmPreferences_cbRecordingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto&amp;matically retry recording deletion.
        /// </summary>
        internal static string FrmPreferences_cbRetryDelete {
            get {
                return ResourceManager.GetString("FrmPreferences_cbRetryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crazysoft AppUpdate was not found. Please install the program before trying to update..
        /// </summary>
        internal static string FrmPreferences_Error_AppUpdate_Text {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_AppUpdate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program not found.
        /// </summary>
        internal static string FrmPreferences_Error_AppUpdate_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_AppUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proxy port must be a number between 0 and 65535..
        /// </summary>
        internal static string FrmPreferences_Error_PortWrong_Text {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_PortWrong_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong proxy port entered.
        /// </summary>
        internal static string FrmPreferences_Error_PortWrong_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_PortWrong_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a proxy address..
        /// </summary>
        internal static string FrmPreferences_Error_ProxyAddress_Text {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_ProxyAddress_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No proxy address entered.
        /// </summary>
        internal static string FrmPreferences_Error_ProxyAddress_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_ProxyAddress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a proxy port..
        /// </summary>
        internal static string FrmPreferences_Error_ProxyPort_Text {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_ProxyPort_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No proxy port entered.
        /// </summary>
        internal static string FrmPreferences_Error_ProxyPort_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_ProxyPort_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a proxy username..
        /// </summary>
        internal static string FrmPreferences_Error_ProxyUser_Text {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_ProxyUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No proxy username entered.
        /// </summary>
        internal static string FrmPreferences_Error_ProxyUser_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_ProxyUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crazysoft AppUpdate could not be started. Please check the program location or reinstall the application.
        ///
        ///{0}.
        /// </summary>
        internal static string FrmPreferences_Error_Update_Text {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_Update_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start program.
        /// </summary>
        internal static string FrmPreferences_Error_Update_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Error_Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright {0}. All rights reserved..
        /// </summary>
        internal static string FrmPreferences_lblCopyright {
            get {
                return ResourceManager.GetString("FrmPreferences_lblCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update check: {0}.
        /// </summary>
        internal static string FrmPreferences_lblLastUpdate {
            get {
                return ResourceManager.GetString("FrmPreferences_lblLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never.
        /// </summary>
        internal static string FrmPreferences_lblLastUpdate_Never {
            get {
                return ResourceManager.GetString("FrmPreferences_lblLastUpdate_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progre&amp;ss Indicator:.
        /// </summary>
        internal static string FrmPreferences_lblProgressIndicator {
            get {
                return ResourceManager.GetString("FrmPreferences_lblProgressIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Address:.
        /// </summary>
        internal static string FrmPreferences_lblProxyAddress {
            get {
                return ResourceManager.GetString("FrmPreferences_lblProxyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwor&amp;d:.
        /// </summary>
        internal static string FrmPreferences_lblProxyPassword {
            get {
                return ResourceManager.GetString("FrmPreferences_lblProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po&amp;rt:.
        /// </summary>
        internal static string FrmPreferences_lblProxyPort {
            get {
                return ResourceManager.GetString("FrmPreferences_lblProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Us&amp;ername:.
        /// </summary>
        internal static string FrmPreferences_lblProxyUser {
            get {
                return ResourceManager.GetString("FrmPreferences_lblProxyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string FrmPreferences_lblSeconds {
            get {
                return ResourceManager.GetString("FrmPreferences_lblSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to the folks at OnlineTVRecorder.com for their great
        ///service.
        ///Thanks to the community at CodeProject.com for their coding
        ///help.
        ///OTR Remote contains parts of the WindowsAPICodePack..
        /// </summary>
        internal static string FrmPreferences_lblThanks {
            get {
                return ResourceManager.GetString("FrmPreferences_lblThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string FrmPreferences_lblVersion {
            get {
                return ResourceManager.GetString("FrmPreferences_lblVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates....
        /// </summary>
        internal static string FrmPreferences_llblUpdate {
            get {
                return ResourceManager.GetString("FrmPreferences_llblUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTR Remote has to be closed before updating it. Any unsaved work will be lost. Do you want to exit the application now?.
        /// </summary>
        internal static string FrmPreferences_Msg_AppUpdate_Text {
            get {
                return ResourceManager.GetString("FrmPreferences_Msg_AppUpdate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitting required.
        /// </summary>
        internal static string FrmPreferences_Msg_AppUpdate_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Msg_AppUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom pro&amp;xy:.
        /// </summary>
        internal static string FrmPreferences_rbCustomProxy {
            get {
                return ResourceManager.GetString("FrmPreferences_rbCustomProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use IE &amp;default proxy settings.
        /// </summary>
        internal static string FrmPreferences_rbDefaultProxy {
            get {
                return ResourceManager.GetString("FrmPreferences_rbDefaultProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string FrmPreferences_Tab_About {
            get {
                return ResourceManager.GetString("FrmPreferences_Tab_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string FrmPreferences_Tab_Network {
            get {
                return ResourceManager.GetString("FrmPreferences_Tab_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string FrmPreferences_Tab_Program {
            get {
                return ResourceManager.GetString("FrmPreferences_Tab_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Preferences.
        /// </summary>
        internal static string FrmPreferences_Title {
            get {
                return ResourceManager.GetString("FrmPreferences_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string FrmProgress_btnClose {
            get {
                return ResourceManager.GetString("FrmProgress_btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close ({0}).
        /// </summary>
        internal static string FrmProgress_btnClose_Countdown {
            get {
                return ResourceManager.GetString("FrmProgress_btnClose_Countdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date respectively the start time have to be in future. Please check them..
        /// </summary>
        internal static string FrmProgress_Error_Date {
            get {
                return ResourceManager.GetString("FrmProgress_Error_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTR website is currently down for maintenance. Please try again later..
        /// </summary>
        internal static string FrmProgress_Error_Maintenance {
            get {
                return ResourceManager.GetString("FrmProgress_Error_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTR Remote has stumbled over an unknown status message. The file {0} has been saved. Please check the recording status manually and send the file to the Crazysoft support to allow an error fix..
        /// </summary>
        internal static string FrmProgress_Error_ParseError {
            get {
                return ResourceManager.GetString("FrmProgress_Error_ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login data you provided is not correct. Please check it..
        /// </summary>
        internal static string FrmProgress_Error_WrongLogin {
            get {
                return ResourceManager.GetString("FrmProgress_Error_WrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection error occured while trying to modify your recording:
        ///
        ///{0}
        ///
        ///Please check your network and proxy settings..
        /// </summary>
        internal static string FrmProgress_ErrorMsg_ConnErr_Text {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_ConnErr_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        internal static string FrmProgress_ErrorMsg_ConnErr_Title {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_ConnErr_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recording could not be deleted. Please check if you really have it in your recording list and username and password are correct..
        /// </summary>
        internal static string FrmProgress_ErrorMsg_DeleteError_Text {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_DeleteError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion Error.
        /// </summary>
        internal static string FrmProgress_ErrorMsg_DeleteError_Title {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_DeleteError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EPG ID for the recording could not be found. Probably, the OTR EPG has a different title for the recording than your EPG or it is too far in future.
        ///Please delete the recording on the OTR website..
        /// </summary>
        internal static string FrmProgress_ErrorMsg_EPGNotFound_Text {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_EPGNotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPG ID not found.
        /// </summary>
        internal static string FrmProgress_ErrorMsg_EPGNotFound_Title {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_EPGNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recording could not be deleted. OTR needs some time before recently added recordings are deletable. If you are sure that this recording is in your recording list, you should try deleting it again in a few minutes.
        ///
        ///Should OTR Remote retry to delete this recording automatically in 10 minutes?.
        /// </summary>
        internal static string FrmProgress_ErrorMsg_NotRecorded {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_NotRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Error.
        /// </summary>
        internal static string FrmProgress_ErrorMsg_Title {
            get {
                return ResourceManager.GetString("FrmProgress_ErrorMsg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}, {2}: {3}.
        /// </summary>
        internal static string FrmProgress_lblCurRec_Full {
            get {
                return ResourceManager.GetString("FrmProgress_lblCurRec_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}: {3}.
        /// </summary>
        internal static string FrmProgress_lblCurRec_NoStation {
            get {
                return ResourceManager.GetString("FrmProgress_lblCurRec_NoStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0 {1}, {2}.
        /// </summary>
        internal static string FrmProgress_lblCurRec_NoTitle {
            get {
                return ResourceManager.GetString("FrmProgress_lblCurRec_NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, while OTR Remote modifies the recording..
        /// </summary>
        internal static string FrmProgress_lblDescription {
            get {
                return ResourceManager.GetString("FrmProgress_lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Progress.
        /// </summary>
        internal static string FrmProgress_lblHeader {
            get {
                return ResourceManager.GetString("FrmProgress_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /patience.php.
        /// </summary>
        internal static string FrmProgress_Result_MaintenanceFileName {
            get {
                return ResourceManager.GetString("FrmProgress_Result_MaintenanceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;You are not allowed to delete this recording!&lt;/b&gt;.
        /// </summary>
        internal static string FrmProgress_Result_NotRecorded {
            get {
                return ResourceManager.GetString("FrmProgress_Result_NotRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVM2OTR:OK.
        /// </summary>
        internal static string FrmProgress_Result_Success {
            get {
                return ResourceManager.GetString("FrmProgress_Result_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVM2OTR:ERROR.
        /// </summary>
        internal static string FrmProgress_Result_TooLate {
            get {
                return ResourceManager.GetString("FrmProgress_Result_TooLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Sie sind nicht eingeloggt.&lt;/b&gt;.
        /// </summary>
        internal static string FrmProgress_Result_WrongLogin {
            get {
                return ResourceManager.GetString("FrmProgress_Result_WrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, aborting....
        /// </summary>
        internal static string FrmProgress_Status_Aborting {
            get {
                return ResourceManager.GetString("FrmProgress_Status_Aborting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for retry of deletion in {0}....
        /// </summary>
        internal static string FrmProgress_Status_DeletionDeferred {
            get {
                return ResourceManager.GetString("FrmProgress_Status_DeletionDeferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action aborted: An error has occured..
        /// </summary>
        internal static string FrmProgress_Status_Error {
            get {
                return ResourceManager.GetString("FrmProgress_Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action was successfully finished..
        /// </summary>
        internal static string FrmProgress_Status_Finished {
            get {
                return ResourceManager.GetString("FrmProgress_Status_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}: {2}.
        /// </summary>
        internal static string FrmProgress_Status_Multiple {
            get {
                return ResourceManager.GetString("FrmProgress_Status_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking IE default proxy settings....
        /// </summary>
        internal static string FrmProgress_Status_Proxy {
            get {
                return ResourceManager.GetString("FrmProgress_Status_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching EPG ID of recording....
        /// </summary>
        internal static string FrmProgress_Status_SearchingEPG {
            get {
                return ResourceManager.GetString("FrmProgress_Status_SearchingEPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the recording job to OTR....
        /// </summary>
        internal static string FrmProgress_Status_Sending {
            get {
                return ResourceManager.GetString("FrmProgress_Status_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, OTR Remote could not delete your recording again..
        /// </summary>
        internal static string FrmProgress_Systray_Deletion_Error {
            get {
                return ResourceManager.GetString("FrmProgress_Systray_Deletion_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTR Remote will stay in your System Tray and try deleting your recording again in 10 minutes..
        /// </summary>
        internal static string FrmProgress_Systray_Deletion_Intro {
            get {
                return ResourceManager.GetString("FrmProgress_Systray_Deletion_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTR Remote has successfully deleted your recording..
        /// </summary>
        internal static string FrmProgress_Systray_Deletion_Success {
            get {
                return ResourceManager.GetString("FrmProgress_Systray_Deletion_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTR Remote (retry in {0}).
        /// </summary>
        internal static string FrmProgress_Systray_Deletion_Timer {
            get {
                return ResourceManager.GetString("FrmProgress_Systray_Deletion_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion Deferred.
        /// </summary>
        internal static string FrmProgress_Systray_Deletion_Title {
            get {
                return ResourceManager.GetString("FrmProgress_Systray_Deletion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string FrmRecordingPreview_AddText {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string FrmRecordingPreview_btnCancel {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string FrmRecordingPreview_btnOK {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daily.
        /// </summary>
        internal static string FrmRecordingPreview_cbSeriesRule_Time {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_cbSeriesRule_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {0}.
        /// </summary>
        internal static string FrmRecordingPreview_cbSeriesRule_TimeAndWeekDay {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_cbSeriesRule_TimeAndWeekDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on weekends.
        /// </summary>
        internal static string FrmRecordingPreview_cbSeriesRule_TimeAndWeekend {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_cbSeriesRule_TimeAndWeekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on workdays.
        /// </summary>
        internal static string FrmRecordingPreview_cbSeriesRule_TimeAndWorkDay {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_cbSeriesRule_TimeAndWorkDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string FrmRecordingPreview_FromText {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_FromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series Recording.
        /// </summary>
        internal static string FrmRecordingPreview_gbSeries {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_gbSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time:.
        /// </summary>
        internal static string FrmRecordingPreview_lblEndTime {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_lblEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre:.
        /// </summary>
        internal static string FrmRecordingPreview_lblGenre {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_lblGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Preview.
        /// </summary>
        internal static string FrmRecordingPreview_lblHeader {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} recording {1} OTR using following data:.
        /// </summary>
        internal static string FrmRecordingPreview_lblIntroduction {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_lblIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers enclosed with { } are incremented with each series recording..
        /// </summary>
        internal static string FrmRecordingPreview_lblNumberHelp {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_lblNumberHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 recording will be processed.
        /// </summary>
        internal static string FrmRecordingPreview_lblRecordingCount {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_lblRecordingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} recordings will be processed.
        /// </summary>
        internal static string FrmRecordingPreview_lblRecordingCount_Multiple {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_lblRecordingCount_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string FrmRecordingPreview_lblSeriesDays {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_lblSeriesDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} recordings for the following.
        /// </summary>
        internal static string FrmRecordingPreview_lblSeriesRecording {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_lblSeriesRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to the same time.
        /// </summary>
        internal static string FrmRecordingPreview_lblSeriesTime {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_lblSeriesTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date:.
        /// </summary>
        internal static string FrmRecordingPreview_lblStartDate {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_lblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time:.
        /// </summary>
        internal static string FrmRecordingPreview_lblStartTime {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_lblStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station:.
        /// </summary>
        internal static string FrmRecordingPreview_lblStation {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_lblStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string FrmRecordingPreview_lblTitle {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string FrmRecordingPreview_RemoveText {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_RemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string FrmRecordingPreview_ToText {
            get {
                return ResourceManager.GetString("FrmRecordingPreview_ToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have read and/or write access to the Station Correction file. Saving of changes is disabled..
        /// </summary>
        internal static string FrmStations_AccessMsg_Text {
            get {
                return ResourceManager.GetString("FrmStations_AccessMsg_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving disabled.
        /// </summary>
        internal static string FrmStations_AccessMsg_Title {
            get {
                return ResourceManager.GetString("FrmStations_AccessMsg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string FrmStations_btnCancel {
            get {
                return ResourceManager.GetString("FrmStations_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;dd.
        /// </summary>
        internal static string FrmStations_btnEPGAdd {
            get {
                return ResourceManager.GetString("FrmStations_btnEPGAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cha&amp;nge.
        /// </summary>
        internal static string FrmStations_btnEPGChange {
            get {
                return ResourceManager.GetString("FrmStations_btnEPGChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;emove.
        /// </summary>
        internal static string FrmStations_btnEPGRemove {
            get {
                return ResourceManager.GetString("FrmStations_btnEPGRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string FrmStations_btnOK {
            get {
                return ResourceManager.GetString("FrmStations_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        internal static string FrmStations_btnOTRAdd {
            get {
                return ResourceManager.GetString("FrmStations_btnOTRAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;hange.
        /// </summary>
        internal static string FrmStations_btnOTRChange {
            get {
                return ResourceManager.GetString("FrmStations_btnOTRChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        internal static string FrmStations_btnOTRRemove {
            get {
                return ResourceManager.GetString("FrmStations_btnOTRRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case-&amp;sensitive station name replacements.
        /// </summary>
        internal static string FrmStations_cbCaseSensitive {
            get {
                return ResourceManager.GetString("FrmStations_cbCaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        internal static string FrmStations_gbAdvanced {
            get {
                return ResourceManager.GetString("FrmStations_gbAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every EPG software has its own name for TV stations. To make sure OTR gets the correct station name, enter the replacements here..
        /// </summary>
        internal static string FrmStations_lblDescription {
            get {
                return ResourceManager.GetString("FrmStations_lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPG Station Replacements:.
        /// </summary>
        internal static string FrmStations_lblEPGStation {
            get {
                return ResourceManager.GetString("FrmStations_lblEPGStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTR Station Names:.
        /// </summary>
        internal static string FrmStations_lblOTRStation {
            get {
                return ResourceManager.GetString("FrmStations_lblOTRStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to save the changes. Please check the file permissions and try again..
        /// </summary>
        internal static string FrmStations_SaveMsg_Text {
            get {
                return ResourceManager.GetString("FrmStations_SaveMsg_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving changes.
        /// </summary>
        internal static string FrmStations_SaveMsg_Title {
            get {
                return ResourceManager.GetString("FrmStations_SaveMsg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Corrections.
        /// </summary>
        internal static string FrmStations_Title {
            get {
                return ResourceManager.GetString("FrmStations_Title", resourceCulture);
            }
        }
    }
}
