//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.1433
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazysoft.OTRRemote.Lang {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TVBrowser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TVBrowser() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crazysoft.OTRRemote.Lang.TVBrowser", typeof(TVBrowser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Close ähnelt.
        /// </summary>
        internal static string FrmWizard_btnClose {
            get {
                return ResourceManager.GetString("FrmWizard_btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Next &gt; ähnelt.
        /// </summary>
        internal static string FrmWizard_btnNext {
            get {
                return ResourceManager.GetString("FrmWizard_btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt; &amp;Previous ähnelt.
        /// </summary>
        internal static string FrmWizard_btnPrevious {
            get {
                return ResourceManager.GetString("FrmWizard_btnPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Step 1: Start TV-Browser ähnelt.
        /// </summary>
        internal static string FrmWizard_lblHeader {
            get {
                return ResourceManager.GetString("FrmWizard_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Step 2: Open the Capture Plugin Settings ähnelt.
        /// </summary>
        internal static string FrmWizard_lblHeader_Step2 {
            get {
                return ResourceManager.GetString("FrmWizard_lblHeader_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Step 3: Create a new device ähnelt.
        /// </summary>
        internal static string FrmWizard_lblHeader_Step3 {
            get {
                return ResourceManager.GetString("FrmWizard_lblHeader_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Step 4: Select OTR Remote as application ähnelt.
        /// </summary>
        internal static string FrmWizard_lblHeader_Step4 {
            get {
                return ResourceManager.GetString("FrmWizard_lblHeader_Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Step 5: Configure the recording parameters ähnelt.
        /// </summary>
        internal static string FrmWizard_lblHeader_Step5 {
            get {
                return ResourceManager.GetString("FrmWizard_lblHeader_Step5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Step 6: Configure the plugin settings ähnelt.
        /// </summary>
        internal static string FrmWizard_lblHeader_Step6 {
            get {
                return ResourceManager.GetString("FrmWizard_lblHeader_Step6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Step 7: Use it! ähnelt.
        /// </summary>
        internal static string FrmWizard_lblHeader_Step7 {
            get {
                return ResourceManager.GetString("FrmWizard_lblHeader_Step7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This wizard will now guide you thorugh the configuration of TV-Browser for OTR Remote. Unfortunately, this can&apos;t be done automatically up to now. ähnelt.
        /// </summary>
        internal static string FrmWizard_lblPage1Header {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First, you have to start TV-Browser, if you haven&apos;t done yet. Simply open TV-Browser as you normally would do. ähnelt.
        /// </summary>
        internal static string FrmWizard_lblPage1Text1 {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage1Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Now, open the Capture Plugin Settings dialog by clicking &quot;Plugins&quot; in the menu bar and selecting &quot;Capture Plugin&quot;. ähnelt.
        /// </summary>
        internal static string FrmWizard_lblPage2Text1 {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage2Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In the settings dialog, create a new device by changing to the &quot;Devices&quot; tab and clicking on &quot;Add Device&quot;. Enter the name &quot;OnlineTvRecorder&quot; and select the Default Driver. Click OK. ähnelt.
        /// </summary>
        internal static string FrmWizard_lblPage3Text1 {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage3Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On the Application tab, copy following text into the Application field: ähnelt.
        /// </summary>
        internal static string FrmWizard_lblPage4Text1 {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage4Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete: ähnelt.
        /// </summary>
        internal static string FrmWizard_lblPage5Delete {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage5Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Record: ähnelt.
        /// </summary>
        internal static string FrmWizard_lblPage5Record {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage5Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On the Parameter tab, copy following text into the Record and the Delete field: ähnelt.
        /// </summary>
        internal static string FrmWizard_lblPage5Text1 {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage5Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On the Settings tab, set the options as shown on the image below. If you know, what these settings do, you can also set them as they fit best for you. ähnelt.
        /// </summary>
        internal static string FrmWizard_lblPage6Text1 {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage6Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have now finished configuring TV-Browser for OTR Remote. After clicking OK in both windows, you are ready to record! ähnelt.
        /// </summary>
        internal static string FrmWizard_lblPage7Header {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage7Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can simply record TV shows by right-clicking them and selecting &quot;Record&quot; from the context menu. Close this wizard by clicking Close in the right bottom corner. ähnelt.
        /// </summary>
        internal static string FrmWizard_lblPage7Text1 {
            get {
                return ResourceManager.GetString("FrmWizard_lblPage7Text1", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FrmWizard_pbHeader {
            get {
                object obj = ResourceManager.GetObject("FrmWizard_pbHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrmWizard_pbPage1Shortcut {
            get {
                object obj = ResourceManager.GetObject("FrmWizard_pbPage1Shortcut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrmWizard_pbPage2CapturePlugin {
            get {
                object obj = ResourceManager.GetObject("FrmWizard_pbPage2CapturePlugin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrmWizard_pbPage3NewDevice {
            get {
                object obj = ResourceManager.GetObject("FrmWizard_pbPage3NewDevice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrmWizard_pbPage4ApplicationTab {
            get {
                object obj = ResourceManager.GetObject("FrmWizard_pbPage4ApplicationTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrmWizard_pbPage5ParameterTab {
            get {
                object obj = ResourceManager.GetObject("FrmWizard_pbPage5ParameterTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrmWizard_pbPage6SettingsTab {
            get {
                object obj = ResourceManager.GetObject("FrmWizard_pbPage6SettingsTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -r -s=&quot;{channel_name}&quot; -sd={concat(start_year, &quot;-&quot;, leadingZero(start_month, &quot;2&quot;), &quot;-&quot;, leadingZero(start_day, &quot;2&quot;))} -st={concat(leadingZero(start_hour, &quot;2&quot;), &quot;:&quot;, leadingZero(start_minute, &quot;2&quot;))} -et={concat(leadingZero(end_hour, &quot;2&quot;), &quot;:&quot;, leadingZero(end_minute, &quot;2&quot;))} -t=&quot;{title}&quot; -g=&quot;{genre}&quot; ähnelt.
        /// </summary>
        internal static string FrmWizard_tbPage5DeleteText {
            get {
                return ResourceManager.GetString("FrmWizard_tbPage5DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -a -s=&quot;{channel_name}&quot; -sd={concat(start_year, &quot;-&quot;, leadingZero(start_month, &quot;2&quot;), &quot;-&quot;, leadingZero(start_day, &quot;2&quot;))} -st={concat(leadingZero(start_hour, &quot;2&quot;), &quot;:&quot;, leadingZero(start_minute, &quot;2&quot;))} -et={concat(leadingZero(end_hour, &quot;2&quot;), &quot;:&quot;, leadingZero(end_minute, &quot;2&quot;))} -t=&quot;{title}&quot; -g=&quot;{genre}&quot; ähnelt.
        /// </summary>
        internal static string FrmWizard_tbPage5RecordText {
            get {
                return ResourceManager.GetString("FrmWizard_tbPage5RecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TV-Browser Plugin Installation Wizard ähnelt.
        /// </summary>
        internal static string FrmWizard_Title {
            get {
                return ResourceManager.GetString("FrmWizard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You don&apos;t have write access to the application path. Please run OTR Remote as an administrator. ähnelt.
        /// </summary>
        internal static string Plugin_Error_AccessDenied {
            get {
                return ResourceManager.GetString("Plugin_Error_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The application path you have entered is invalid. Please check it. ähnelt.
        /// </summary>
        internal static string Plugin_Error_Invalid_Path {
            get {
                return ResourceManager.GetString("Plugin_Error_Invalid_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application Path ähnelt.
        /// </summary>
        internal static string Plugin_Settings_Path {
            get {
                return ResourceManager.GetString("Plugin_Settings_Path", resourceCulture);
            }
        }
    }
}
